import {ReactNode} from "react";
import type { Metadata } from 'next'
import Sidebar from "@/components/sideBar/Sidebar";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
	title: 'Routiner dashboard',
	description: 'Generated by create next app',
}

export default function HomeLayout({children}: {children: ReactNode}) {
	return (
		<html lang="en">
			<body>
			<div className='wrapper'>
				<Sidebar />
				<div className='wrapper-content'>
					<Navbar />
					{children}
				</div>
			</div>
			</body>
		</html>
	);
}
